version: "3.9"
services:
    api:
        build: .
        command: python api.py
        ports:
            - "8080:8080"
        environment:
            - PORT=8080
            - NET_DB_PATH=/data/app.db
            - ALLOWED_ORIGINS=http://localhost:3000
        volumes:
            - ./data:/data
        env_file:
            - .env
volumes:
    data:
        driver: local
