version: "3.9"
services:
    api:
        build: .
        command: gunicorn -w 1 -k gthread --threads 8 -b 0.0.0.0:${PORT:-8080} api:app
        ports:
            - "8080:8080"
        environment:
            - PORT=8080
            - ALLOWED_ORIGINS=http://localhost:3000
        env_file:
            - .env
